[package]
name = "fulmen-net"
description = "Connection layer for Fulmen: talks to Minecraft: Java Edition servers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
fulmen-protocol.workspace = true
flate2.workspace = true
md-5.workspace = true
serde.workspace = true
serde_json.workspace = true
