[workspace]
resolver = "3"
members = [
    # "crates/fulmen",
    # "crates/fulmen-auth",
    # "crates/fulmen-client",
    # "crates/fulmen-core",
    "crates/fulmen-net",
    "crates/fulmen-protocol",
    # "crates/fulmen-render",
    # "crates/fulmen-world",
    "launcher/src-tauri",
]
default-members = [
    # "crates/fulmen",
    # "crates/fulmen-auth",
    # "crates/fulmen-client",
    # "crates/fulmen-core",
    "crates/fulmen-net",
    "crates/fulmen-protocol",
    # "crates/fulmen-render",
    # "crates/fulmen-world",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "GPL-3.0-or-later"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }

[profile.dev.package."*"]
opt-level = 2

[profile.release]
lto = true
strip = "debuginfo"
codegen-units = 1

[workspace.dependencies]
fulmen-protocol = { path = "crates/fulmen-protocol" }
fulmen-net = { path = "crates/fulmen-net" }

serde = { version = "1", features = ["derive"] }
serde_json = "1.0.151"

flate2 = "1"
md-5 = "0.10"